[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=native"]
rustdocflags = ["-Ctarget-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native", "-Ctarget-feature=+avx2,+avx512f"]
rustdocflags = ["-Ctarget-cpu=native", "-Ctarget-feature=+avx2,+avx512f"]
